version: "2"
services:
  dev:
    build: .
    restart: always
    tty: true
    command: npm run serve
    volumes:
      - ./studium/hosting:/src
    working_dir: "/src"
    ports:
      - "8080:8080"

